// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verifactu.Data;

#nullable disable

namespace Verifactu.Data.Migrations
{
    [DbContext(typeof(VerifactuDbContext))]
    partial class VerifactuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Verifactu.Data.Entities.RegistroFacturacionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcuseRecibo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("CSV")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CodigoErrorAEAT")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionErrorAEAT")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraExpedicionUTC")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimoEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HuellaAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NifEmisor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmisor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefExterna")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reintentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlFirmado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoEnvio")
                        .HasDatabaseName("IX_RegistrosFacturacion_EstadoEnvio");

                    b.HasIndex("FechaHoraExpedicionUTC")
                        .HasDatabaseName("IX_RegistrosFacturacion_FechaHoraExpedicionUTC");

                    b.HasIndex("Huella")
                        .HasDatabaseName("IX_RegistrosFacturacion_Huella");

                    b.HasIndex("NifEmisor")
                        .HasDatabaseName("IX_RegistrosFacturacion_NifEmisor");

                    b.HasIndex("Serie", "Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_RegistrosFacturacion_Serie_Numero");

                    b.HasIndex(new[] { "EstadoEnvio" }, "IX_RegistrosFacturacion_EstadoEnvio");

                    b.HasIndex(new[] { "FechaHoraExpedicionUTC" }, "IX_RegistrosFacturacion_FechaHoraExpedicionUTC");

                    b.HasIndex(new[] { "Huella" }, "IX_RegistrosFacturacion_Huella");

                    b.HasIndex(new[] { "Serie", "Numero" }, "IX_RegistrosFacturacion_Serie_Numero")
                        .IsUnique();

                    b.ToTable("RegistrosFacturacion");
                });
#pragma warning restore 612, 618
        }
    }
}
